services:
  notes:
    container_name: notes_container
    hostname: notes
    restart: always
    build:
      context: .
      args:
          - PASSWORD=root
    ports:
      - "12000:8000"
      - "12022:22"
    environment:
      - FLAG=dummyflag{fake_flag}