services:
  notes:
    container_name: notes_container
    hostname: notes
    restart: always
    ports:
      - "12000:8000"
      - "12022:22"
    build:
      context: Notes
      args:
          - PASSWORD=$PASSWORD_12000
    volumes:
      - ../receiver/flags/notes.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"